version: '3'

services:
  asterios-web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: 'asterios-bot-web'
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    networks:
      - tier

  asterios:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: 'asterios-bot-php'
    restart: always
    volumes:
      - .:/app/
    networks:
      - tier

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: 'asterios-bot-worker'
    restart: always
    volumes:
      - .:/app/
    networks:
      - tier

networks:
  tier:
    external:
      name: telegram-bots-network