version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: 'asterios-bot-web'
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - telegram-bots-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: 'asterios-bot-php'
    restart: always
    volumes:
      - .:/app/
    links:
      - mysql
      - redis
    networks:
      - telegram-bots-network

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: 'asterios-bot-worker'
    restart: always
    volumes:
      - .:/app/
    links:
      - mysql
      - redis
    networks:
      - telegram-bots-network

  mysql:
    image: mysql:5.7.22
    container_name: 'asterios-bot-mysql'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: asterios
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - telegram-bots-network

  redis:
    container_name: 'asterios-bot-redis'
    image: redis:3.2
    restart: always
    ports:
      - "127.0.0.1:6379:6379/tcp"
    networks:
      - telegram-bots-network

networks:
  telegram-bots-network:
    driver: bridge